// export const apiBaseUrl: string = "http://localhost:4000/api";
export const apiBaseUrl: string = "https://tilawat-dashboard-api.herokuapp.com/api";

export const studentRoutes = {
    Base: "student",
    List: "list",
    View: "view",
    Add: "addTilawat"
};

export const reportTypeList = [
    { id: "Individual Report", text: "Individual Report" },
    { id: "Overall Report", text: "Overall Report" },
]

export const surats = [
    "Al-Fatihah", 
    "Al-Baqarah",
    "Al-'Imran ",
    "An-Nisa",              
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "Al-Bara'at",
    "Yunus",
    "Hud",
    "Yusuf", 
    "Ar-Ra'd", 
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Bani Isra'il",
    "Al-Kahf",
    "Maryam",
    "Ta Ha",
    "Al-Anbiya", 
    "Al-Hajj",
    "Al-Mu'minun", 
    "An-Nur",
    "Al-Furqan", 
    "Ash-Shu'ara'", 
    "An-Naml",
    "Al-Qasas",
    "Al-'Ankabut", 
    "Ar-Rum",
    "Luqman",
    "As-Sajdah", 
    "Al-Ahzab",
    "Al-Saba",
    "Al-Fatir",
    "Ya Sin",
    "As-Saffat", 
    "Sad",
    "Az-Zumar", 
    "Al-Mu'min",
    "Ha Mim",
    "Ash-Shura", 
    "Az-Zukhruf", 
    "Ad-Dukhan",
    "Al-Jathiyah", 
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat", 
    "Qaf",
    "Ad-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'ah",
    "Al-Hadid",
    "Al-Mujadilah", 
    "Al-Hashr",
    "Al-Mumtahanah", 
    "As-Saff",
    "Al-Jumu'ah", 
    "Al-Munafiqun", 
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn", 
    "Al-Muzzammil", 
    "Al-Muddaththir", 
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat", 
    "An-Naba",
    "An-Nazi'at", 
    "'Abasa",
    "At-Takwir", 
    "Al-Infitar",
    "At-Tatfif",
    "Al-Inshiqaq", 
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr", 
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Al-Inshirah", 
    "At-Tin",
    "Al-'Alaq", 
    "Al-Qadr",
    "Al-Bayyinah", 
    "Al-Zilzal",
    "Al-'Adiyat",
    "Al-Qari'ah",
    "At-Takathur",
    "Al-'Asr",
    "Al-Humazah", 
    "Al-Fil",
    "Al-Quraish", 
    "Al-Ma'un",
    "Al-Kauthar", 
    "Al-Kafirun",
    "An-Nasr",
    "Al-Lahab",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas",
    ]